name:                sturdy-backwards
version:             0.2.0.0
license:             BSD3
maintainer:          Sven Keidel <svenkeidel@gmail.com>
category:            Language

dependencies:
  - base
  - deepseq
  - hashable
  - sturdy-lib
  - text
  - unordered-containers
  - prettyprinter

library:
  source-dirs:
    - src

  ghc-options: -Wall


tests:
  spec:
    main: Spec.hs

    source-dirs:
      - test

    ghc-options: -Wall

    dependencies:
      - sturdy-backwards
      - hspec
